using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/**Problem 2 from Project Euler
 * Each new term in the Fibonaci sequence is generated by adding the previous two terms. By starting
 * with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed 4 million,
 * find the sum of the even-valued terms.
 **/
namespace EvenFibonacciNumbers
{
    class Program
    {
        static void Main(string[] args)
        {
        }
    }
}
